{{- with $.Values.serviceAccount -}}
{{- if .create -}}
---
apiVersion: v1
automountServiceAccountToken: {{ .automount | default true }}
kind: ServiceAccount
metadata:
  labels: {{- include "druid.labels" $ | nindent 4 }}
  name: {{ include "druid.serviceAccountName" $ }}
{{- end }}
{{- end }}
