apiVersion: v2
dependencies:
  - name: druid
    repository: file://../druid
    version: ^0.7.0-beta14
  - condition: operator.enabled
    alias: operator
    name: druid-operator
    repository: https://charts.datainfra.io
    version: ^0.3.9
  - condition: metricsServer.enabled
    alias: metricsServer
    name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server
    version: ^3.12.2
  - condition: minio.enabled
    name: minio
    repository: https://charts.bitnami.com/bitnami
    version: ^16.0.7
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ^16.6.3
description: A Helm chart for deploying Apache Druid in a development environment
home: https://github.com/bsure-analytics/druid-chart
keywords:
  - Apache Druid
  - Druid
  - development
  - dev
maintainers:
  - name: Christian Schlichtherle
    url: https://github.com/christian-schlichtherle
name: druid-dev
sources:
  - https://github.com/bsure-analytics/druid-chart/charts/druid-dev/tree/main
version: 0.7.0-beta14
