druid:
  secret:
    stringData:
      AWS_ACCESS_KEY_ID: minio
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: minio123
  spec:
    commonRuntimeProperties:
      druid:
        s3:
          enablePathStyleAccess: true
          endpoint.signingRegion: us-east-1
          endpoint.url: http://druid-minio:9000/
          protocol: http
    metadataStorage:
      connector:
        connectURI: jdbc:postgresql://druid-postgresql/druid
        password: druid
        user: druid
    nodes:
      brokers:
        autoscaling:
          replicas:
            max: 3
            min: 1
          metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 50
        resources:
          requests:
            cpu: "1"
global:
  defaultStorageClass: standard
  defaultStorageSize: 10Gi
metricsServer:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
  enabled: true
  nameOverride: metrics-server
minio:
  auth:
    rootPassword: minio123
    rootUser: minio
  defaultBuckets: druid
  enabled: true
nameOverride: druid
operator:
  enabled: true
postgresql:
  auth:
    database: druid
    enablePostgresUser: false
    password: druid
    username: druid
  enabled: true
