{{- with $.Values.roleBinding -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "druid.annotations" . | nindent 2 }}
  labels: {{- include "druid.labels" $ | nindent 4 }}
  name: {{ include "druid.fullname" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "druid.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "druid.serviceAccountName" $ }}
{{- end }}
