{{- with $.Values.secret }}
---
apiVersion: v1
{{- with .data}}
data: {{- toYaml . | nindent 2 }}
{{- end }}
kind: Secret
metadata:
  labels: {{- include "druid.labels" $ | nindent 4 }}
  name: {{ include "druid.fullname" $ }}
{{- with .stringData}}
stringData: {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
